version: '3'

services:
  api:
    build: . 
    ports:
      - "80:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - MEM_DB_HOST=${MEM_DB_HOST:-redis}
      - MEM_DB_PORT=${MEM_DB_PORT:-6379}
      - MEM_DB_PASSWORD=${MEM_DB_PASSWORD}
    depends_on:
      - redis
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
